// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIv-IODJ5Ac-cl7085BjdILeAV93jmIKw',
    appId: '1:915379460830:web:8e45b1e95c298d11df004f',
    messagingSenderId: '915379460830',
    projectId: 'minibuscrm',
    authDomain: 'minibuscrm.firebaseapp.com',
    databaseURL: 'https://minibuscrm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'minibuscrm.firebasestorage.app',
    measurementId: 'G-ES0LCTBWGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHIKS8EW1t72Q51o0Qh1ObscZly3-qmUs',
    appId: '1:915379460830:android:891d70d5c5874a3ddf004f',
    messagingSenderId: '915379460830',
    projectId: 'minibuscrm',
    databaseURL: 'https://minibuscrm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'minibuscrm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy5klEnhQsdIW7EKtgO3_9n62GYJV4FkA',
    appId: '1:915379460830:ios:45c7217d7aac1746df004f',
    messagingSenderId: '915379460830',
    projectId: 'minibuscrm',
    databaseURL: 'https://minibuscrm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'minibuscrm.firebasestorage.app',
    iosBundleId: 'com.example.minibusTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy5klEnhQsdIW7EKtgO3_9n62GYJV4FkA',
    appId: '1:915379460830:ios:45c7217d7aac1746df004f',
    messagingSenderId: '915379460830',
    projectId: 'minibuscrm',
    databaseURL: 'https://minibuscrm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'minibuscrm.firebasestorage.app',
    iosBundleId: 'com.example.minibusTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIv-IODJ5Ac-cl7085BjdILeAV93jmIKw',
    appId: '1:915379460830:web:25a9335d53413529df004f',
    messagingSenderId: '915379460830',
    projectId: 'minibuscrm',
    authDomain: 'minibuscrm.firebaseapp.com',
    databaseURL: 'https://minibuscrm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'minibuscrm.firebasestorage.app',
    measurementId: 'G-TPTYQ1GH1X',
  );

}